global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    metrics_path: '/q/metrics/prometheus'
    static_configs:
      - targets: [ 'api:8081' ]
  - job_name: 'backend'
    metrics_path: '/q/metrics/prometheus'
    static_configs:
      - targets: [ 'backend:8083' ]
  - job_name: 'kafka'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'kafka:9092' ]


